// <auto-generated />
using System;
using MacAddress.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MacAddress.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241008081503_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MacAddress.Models.MacAddresses", b =>
                {
                    b.Property<int>("MacAddId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MacAddId"));

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MacAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramInAgency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingGroup")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MacAddId");

                    b.ToTable("macaddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
